AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple template to create ec2 instance'

Resources:
  EC2SecurityGroup:
       Type: AWS::EC2::SecurityGroup
       Properties:
           VpcId: 'vpc-c0e505b8'
           GroupDescription: SecurityGroup to be attached to this ec2
           SecurityGroupIngress:
               # Only allow inbound access to ECS from the ELB
               - CidrIp: '0.0.0.0/0'
                 FromPort: -1
                 ToPort: -1
                 IpProtocol: -1
           Tags:
               - Key: Name
                 Value: 'CF-test-sg'
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: 'subnet-0103565b'
      InstanceType: 't2.micro'
      SecurityGroupIds: ['sg-83b767f3']
      KeyName: 'cf-test'
      ImageId: 'ami-a9d09ed1'
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, AvailabilityZone]
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]
